2025-02-25 12:30:17.780 | INFO     | datatrove.utils.logging:add_task_logger:58 - Launching pipeline for rank=6
2025-02-25 12:30:17.780 | INFO     | datatrove.utils.logging:log_pipeline:90 - 
--- 🛠️ PIPELINE 🛠
📖 - READER: 📒 Parquet
<__main__.SizeLimitFilter object at 0x7faec5046250>
💽 - WRITER: 📒 Parquet
2025-02-25 12:30:17.780 | ERROR    | datatrove.executor.base:_run_for_rank:108 - SizeLimitFilter.__call__() takes 2 positional arguments but 4 were given
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/home/andbu/miniconda3/envs/llms/lib/python3.11/site-packages/multiprocess/forkserver.py", line 273, in main
    code = _serve_one(child_r, fds,
           │          │        └ [21, 22, 23, 24, 25, 26]
           │          └ 8
           └ <function _serve_one at 0x7faec68342c0>
  File "/home/andbu/miniconda3/envs/llms/lib/python3.11/site-packages/multiprocess/forkserver.py", line 312, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
           │     │     │        └ 4
           │     │     └ 8
           │     └ <function _main at 0x7faec6823420>
           └ <module 'multiprocess.spawn' from '/home/andbu/miniconda3/envs/llms/lib/python3.11/site-packages/multiprocess/spawn.py'>
  File "/home/andbu/miniconda3/envs/llms/lib/python3.11/site-packages/multiprocess/spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 4
           │    └ <function BaseProcess._bootstrap at 0x7faec6da0b80>
           └ <ForkServerProcess name='ForkServerPoolWorker-11' parent=19533 started daemon>
  File "/home/andbu/miniconda3/envs/llms/lib/python3.11/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7faec6da00e0>
    └ <ForkServerProcess name='ForkServerPoolWorker-11' parent=19533 started daemon>
  File "/home/andbu/miniconda3/envs/llms/lib/python3.11/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <ForkServerProcess name='ForkServerPoolWorker-11' parent=19533 started daemon>
    │    │        │    └ (<multiprocess.queues.SimpleQueue object at 0x7faec5022790>, <multiprocess.queues.SimpleQueue object at 0x7faec5035b50>, None...
    │    │        └ <ForkServerProcess name='ForkServerPoolWorker-11' parent=19533 started daemon>
    │    └ <function worker at 0x7faec502c4a0>
    └ <ForkServerProcess name='ForkServerPoolWorker-11' parent=19533 started daemon>
  File "/home/andbu/miniconda3/envs/llms/lib/python3.11/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    │     │       └ {}
                    │     └ (6,)
                    └ functools.partial(<bound method LocalPipelineExecutor._launch_run_for_rank of <datatrove.executor.local.LocalPipelineExecutor...
  File "/home/andbu/miniconda3/envs/llms/lib/python3.11/site-packages/datatrove/executor/local.py", line 76, in _launch_run_for_rank
    return self._run_for_rank(rank, local_rank)
           │    │             │     └ 6
           │    │             └ 6
           │    └ <function PipelineExecutor._run_for_rank at 0x7faec515f560>
           └ <datatrove.executor.local.LocalPipelineExecutor object at 0x7faec520f950>
> File "/home/andbu/miniconda3/envs/llms/lib/python3.11/site-packages/datatrove/executor/base.py", line 90, in _run_for_rank
    pipelined_data = pipeline_step(pipelined_data, rank, self.world_size)
                     │             │               │     │    └ <property object at 0x7faec6848360>
                     │             │               │     └ <datatrove.executor.local.LocalPipelineExecutor object at 0x7faec520f950>
                     │             │               └ 6
                     │             └ <generator object BaseDiskReader.run at 0x7faec6f42df0>
                     └ <__main__.SizeLimitFilter object at 0x7faec5046250>

TypeError: SizeLimitFilter.__call__() takes 2 positional arguments but 4 were given
